version: '3.8'
services:
  wildlife_rag:
    image: wildlife_rag:latest
    build: .
    ports:
      - 8711:8711
      - 5678:5678
    volumes:
      - ./backend:/app
      - ./models--Qdrant--SPLADE_PP_en_v1:/tmp/fastembed_cache/models--Qdrant--SPLADE_PP_en_v1
    command: uvicorn src.main:app --host 0.0.0.0 --port 8711 --reload
    restart: always
    # depends_on:
      #- ollama
      # - qdrant

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/qdrant_storage:/qdrant/storage

  phoenix:
    image: arizephoenix/phoenix:latest # Must be greater than 4.0 version to work
    ports:
      - 6006:6006  # PHOENIX_PORT
      - 4317:4317  # PHOENIX_GRPC_PORT
      - 9090:9090  # [Optional] PROMETHEUS PORT IF ENABLED
    environment:
      - PHOENIX_WORKING_DIR=/mnt/data
    volumes:
      - ./data/phoenix_data:/mnt/data   # PHOENIX_WORKING_DIR
